import type { Metadata } from "next";
import { Oswald, SUSE } from "next/font/google";
import {
  ClerkProvider
} from '@clerk/nextjs'
import "./globals.css";
import Provider from './provider'
import { Toaster } from "@/components/ui/sonner"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bebas = SUSE({weight: '400',subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClerkProvider>
    <html lang="en">
      <body
        className={bebas.className}
      >
        <Provider>
        {children}
        </Provider>
                <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
